---
- name: "Get stat for all required files/dirs in repo: {{ AYAQA_APP_GIT_REPO }}"
  stat:
    path: "{{ item }}"
  with_items: "{{ build_all_required_paths }}"
  register: ifexists
  tags: 
    - provision

- name: "Fail if required dir/file is not found"
  fail: 
    msg: "Folder {{ item }} is required to build {{ AYAQA_PROJECT_NAME }} image."
  when: item.stat.exists != true
  with_items: "{{ ifexists.results }}"
  tags: 
    - provision

- name: "Copy env file in proper location"
  copy:
    src: "{{ build_env_prod_file_full_path }}"
    dest: "{{ build_root_app_dir }}.env"
    mode: '0744'
  tags: 
    - provision

- name: "Ensure proper file permission for install script"
  file:
    dest: "{{ build_install_script_full_path }}"
    mode: a+x
  tags: 
    - provision

- name: "Run provision script from dev repo"
  shell: |
    {{ build_install_script_full_path }}
  args:
    chdir: "{{ build_root_app_dir }}"
  tags: 
    - provision

# Clean task
- name: "Clean: Remove build folder because is not needed"
  file:
    path: "{{ build_tmp_dir }}"
    state: absent
  tags: 
    - clean

# Clean task
- name: "Clean: Remove not needed files from dev repo"
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ git_repo_file_remove_list }}"
  tags: 
    - clean