---
- hosts: localhost
  connection: local
  vars_files:
    - "./provision_vars.json"
    - "./provision_vars_dynamic.json"
  vars:
    ansible_python_interpreter: /usr/bin/python
    list_of_packages: [
      "sqlite3",
      "php8.0-sqlite3"
    ]

  tasks:
    - name: "DEBUG: Dump variables."
      debug:
        msg:
          - "----------------- Vars ---------------------"
          - "Name: {{ AYAQA_IMAGE_NAME }}"
          - "Tag: {{ AYAQA_IMAGE_TAG }}"
          - "Build Stage: {{ AYAQA_INFRA_BUILD_STAGE }}"
          - "Build Debug: {{ AYAQA_INFRA_DEBUG }}"
          - "App Stage: {{ AYAQA_APP_ENV }}"
          - "App Debug: {{ AYAQA_APP_DEBUG }}"
          - "----------------- End ---------------------"
      tags:
        - debug_info

  roles:
    - common