---
- hosts: localhost
  connection: local
  vars_files:
    - "./provision_vars.json"
    - "./provision_vars_dynamic.json"

  vars:
    ansible_python_interpreter: /usr/bin/python
    image_entry_file_path: "{{ AYAQA_ENTRYPOINT_BASH_SCRIPT_PATH }}"
    default_entry_file_path: "{{ AYAQA_INFRA_ENTRYPOINT_FILE_PATH }}"

  tasks:
    - name: "DEBUG: Dump variables."
      debug:
        msg:
          - "----------------- Vars ---------------------"
          - "Name: {{ AYAQA_IMAGE_NAME }}"
          - "Tag: {{ AYAQA_IMAGE_TAG }}"
          - "Build Stage: {{ AYAQA_INFRA_BUILD_STAGE }}"
          - "Build Debug: {{ AYAQA_INFRA_DEBUG }}"
          - "App Stage: {{ AYAQA_APP_ENV }}"
          - "App Debug: {{ AYAQA_APP_DEBUG }}"
          - "----------------- ### ---------------------"
          - "Default entry file path: {{ default_entry_file_path }}"
          - "Current image entry path: {{ image_entry_file_path }}"
          - "----------------- End ---------------------"
      tags:
        - debug_info

  roles:
    - ayaqa-configure