---
- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - "./provision_vars.json"
    - "./provision_vars_dynamic.json"

  vars:
    ansible_python_interpreter: /usr/bin/python
    git_repo: '{{ AYAQA_APP_GIT_REPO }}'
    git_repo_tag: '{{ AYAQA_APP_GIT_TAG }}'
    git_repo_root_dir: '{{ AYAQA_APP_GIT_ROOT_APP_DIR }}'
    git_repo_build_dir: '{{ AYAQA_APP_GIT_BUILD_DIR }}'

    build_root_app_dir: '{{ AYAQA_APP_ROOT_DIR }}'
    git_clone_tmp_dir: '{{ AYAQA_APP_GIT_CLONE_TMP_DIR }}'

    # build dir relative path from dev repo
    build_tmp_dir: '{{ git_clone_tmp_dir }}{{ AYAQA_APP_GIT_BUILD_DIR }}'
    
    build_install_script_name: 'app_install.sh'
    build_install_script_full_path: '{{ build_tmp_dir }}/{{ build_install_script_name }}'

    build_env_prod_file_name: '.app.env'
    build_env_prod_file_full_path: '{{ build_tmp_dir }}/{{ build_env_prod_file_name }}'

    build_all_required_paths:
      - '{{ build_tmp_dir }}'
      - '{{ build_install_script_full_path }}'
      - '{{ build_env_prod_file_full_path }}'

    git_repo_file_remove_list:
      - "{{ build_root_app_dir }}/tests"
      - "{{ build_root_app_dir }}/.env.bak"
      - "{{ build_root_app_dir }}/.env.example"
      - "{{ build_root_app_dir }}/.env.example.bak"
      - "{{ build_root_app_dir }}/.gitattributes"
      - "{{ build_root_app_dir }}/.gitignore"
      - "{{ build_root_app_dir }}/.styleci.yml"
      - "{{ build_root_app_dir }}/README.md"
      - "{{ build_root_app_dir }}/composer.json"
      - "{{ build_root_app_dir }}/composer.lock"
      - "{{ build_root_app_dir }}/docker-compose.yml"
      - "{{ build_root_app_dir }}/package.json"
      - "{{ build_root_app_dir }}/phpunit.xml"
      - "{{ build_root_app_dir }}/server.php"
      - "{{ build_root_app_dir }}/webpack.mix.js"
      - "{{ build_root_app_dir }}/.editorconfig"
  
  tasks:
    - name: "DEBUG: Dump variables."
      debug:
        msg:
          - "----------------- Vars ---------------------"
          - "Name: {{ AYAQA_INFRA_IMAGE_NAME }}"
          - "Tag: {{ AYAQA_INFRA_IMAGE_TAG }}"
          - "Build Stage: {{ AYAQA_INFRA_BUILD_STAGE }}"
          - "Build Debug: {{ AYAQA_INFRA_DEBUG }}"
          - "App Stage: {{ AYAQA_APP_ENV }}"
          - "App Debug: {{ AYAQA_APP_DEBUG }}"
          - "----------------- ### ---------------------"
          - "Build dir dev repo relative path: {{ git_repo_build_dir }}"
          - "Build dir full tmp path: {{ build_tmp_dir }}"
          - "----------------- End ---------------------"
      tags:
        - debug_info

  roles:
    - ayaqa-build