# Dirs
######
DOCKER_BASE_DIR=${ROOT_INFRA_DIR}/docker
IMAGES_BASE_DIR=${DOCKER_BASE_DIR}/images
SHARED_FS_DIR=${DOCKER_BASE_DIR}/sharedfs
COMMON_CONFIG_DIR=${DOCKER_BASE_DIR}/configs

# Files
#######
CONFIG_JSON_MAIN_FILE_NAME=config.json
CONFIG_JSON_MAIN_FILE_PATH=${ROOT_INFRA_DIR}/${CONFIG_JSON_MAIN_FILE_NAME}

CONFIG_JSON_LOCAL_FILE_NAME=config-local.json
CONFIG_JSON_LOCAL_FILE_PATH=${ROOT_INFRA_DIR}/${CONFIG_JSON_LOCAL_FILE_NAME}

CONFIG_JSON_GENERATED_FILE_NAME=config-generated.json
CONFIG_JSON_GENERATED_FILE_PATH=${ROOT_INFRA_DIR}/${CONFIG_JSON_GENERATED_FILE_NAME}

# Common paths to files
PACKER_VARS_FILE_NAME=packer-only-vars.json
PACKER_VARS_FILE_PATH=${COMMON_CONFIG_DIR}/${PACKER_VARS_FILE_NAME}

PROVISION_VARS_FILE_NAME=provision-only-vars.json
PROVISION_VARS_FILE_PATH=${COMMON_CONFIG_DIR}/${PROVISION_VARS_FILE_NAME}

PROVISION_VARS_DYNAMIC_FILE_NAME=provision_vars_dynamic.json
PROVISION_VARS_DYNAMIC_FILE_PATH=${PROVISION_CONFIG_DIR}/${PROVISION_VARS_DYNAMIC_FILE_NAME}

SHARED_VARS_FILE_NAME=shared-vars.json
SHARED_VARS_FILE_PATH=${COMMON_CONFIG_DIR}/${SHARED_VARS_FILE_NAME}