# DIRs paths
######
FILES_DIR=${ROOT_INFRA_DIR}/files
IMAGES_BASE_DIR=${FILES_DIR}/images
SHARED_FS_DIR=${FILES_DIR}/sharedfs
VARS_DIR=${FILES_DIR}/vars
OVERRIDABLE_VARS_DIR=${VARS_DIR}/overridable

# Configs 
#########
CONFIG_JSON_MAIN_FILE_NAME=config.json
CONFIG_JSON_MAIN_FILE_PATH=${ROOT_INFRA_DIR}/${CONFIG_JSON_MAIN_FILE_NAME}

CONFIG_JSON_LOCAL_FILE_NAME=config-local.json
CONFIG_JSON_LOCAL_FILE_PATH=${ROOT_INFRA_DIR}/${CONFIG_JSON_LOCAL_FILE_NAME}

CONFIG_JSON_GENERATED_FILE_NAME=config-generated.json
CONFIG_JSON_GENERATED_FILE_PATH=${ROOT_INFRA_DIR}/${CONFIG_JSON_GENERATED_FILE_NAME}

# File paths to vars and constants
##################################
PACKER_VARS_FILE_NAME=packer-vars.json
PACKER_VARS_FILE_PATH=${OVERRIDABLE_VARS_DIR}/${PACKER_VARS_FILE_NAME}

PROVISION_VARS_FILE_NAME=provision-vars.json
PROVISION_VARS_FILE_PATH=${OVERRIDABLE_VARS_DIR}/${PROVISION_VARS_FILE_NAME}

SHARED_VARS_FILE_NAME=shared-vars.json
SHARED_VARS_FILE_PATH=${OVERRIDABLE_VARS_DIR}/${SHARED_VARS_FILE_NAME}

CONSTANTS_FILE_NAME=constants.json
CONSTANTS_FILE_PATH=${VARS_DIR}/${CONSTANTS_FILE_NAME}

# Depending on dynamic variables from Makefile `PROVISION_CONFIG_DIR`
#####################################################################
PROVISION_VARS_DYNAMIC_FILE_NAME=provision_vars_dynamic.json
PROVISION_VARS_DYNAMIC_FILE_PATH=${PROVISION_CONFIG_DIR}/${PROVISION_VARS_DYNAMIC_FILE_NAME}