---
- name: Include apt install tasks
  include_tasks:
    file: "install-{{ ansible_distribution | lower }}.yml"
    apply:
      tags: 
        - provision
        - install
  tags: 
    - provision
    - install