---
- name: "Set container tz to: {{ timezone }}"
  timezone:
    name: "{{ timezone }}"
  tags: 
    - configure-timezone

- name: Set locales
  shell: |
    echo "LC_ALL=en_US.UTF-8" >> /etc/environment
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
    echo "LANG=en_US.UTF-8" > /etc/locale.conf
    locale-gen en_US.UTF-8
