---
- hosts: localhost
  connection: local
  vars_files:
    - "./provision_vars.json"
    - "./provision_vars_dynamic.json"
  vars:
    ansible_python_interpreter: /usr/bin/python
    timezone: "{{ AYAQA_CONTAINER_TZ }}"
    list_of_packages: [
      "curl",
      "nano",
      "locate",
      "git",
      "locales",
      "iputils-ping",
      "htop",
      "zip",
      "unzip",
      "wget"
    ]
    image_entry_file_path: "{{ AYAQA_ENTRYPOINT_BASH_SCRIPT_PATH }}"
    default_entry_file_path: "{{ AYAQA_IMAGE_ENTRYPOINT_FILE_PATH }}"

  tasks:
    - name: "DEBUG: Dump variables."
      debug:
        msg:
          - "----------------- Vars ---------------------"
          - "Name: {{ AYAQA_PROJECT_NAME }}"
          - "Tag: {{ AYAQA_PROJECT_TAG }}"
          - "Build Stage: {{ AYAQA_PROJECT_BUILD_STAGE }}"
          - "Build Debug: {{ AYAQA_PROJECT_DEBUG }}"
          - "App Stage: {{ AYAQA_APP_ENV }}"
          - "App Debug: {{ AYAQA_APP_DEBUG }}"
          - "----------------- ### ---------------------"
          - "Timezone: {{ timezone }}"
          - "Apt packages: {{ list_of_packages | join(', ') }}"
          - "Default entry file path: {{ default_entry_file_path }}"
          - "Current image entry path: {{ image_entry_file_path }}"
          - "----------------- End ---------------------"
      tags:
        - debug_info

  roles:
    - ayaqa
    - ayaqa-configure