---
# FIX for ansible role instaling sshd.
- name: Ensure /run/sshd dir exists
  file:
    path: /run/sshd
    state: directory
    mode: 0755

- name: Ensure /root/.ssh/ dir exists
  file:
    path: /root/.ssh/
    state: directory
    mode: 0700
