---
- name: Ensure apt packages are installed
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
    update_cache: true
  loop: "{{ list_of_packages }}"
  tags: 
    - install-pkg-apt