---
- hosts: localhost
  connection: local
  vars_files:
    - "./provision_vars.json"
    - "./provision_vars_dynamic.json"
  vars:
    ansible_python_interpreter: /usr/bin/python
    php_version: "{{ AYAQA_PHP_VERSION }}"
    php_cli_config_dir: "{{ AYAQA_PHP_CLI_CONFIG_DIR }}"
    php_xdebug_module_config_file: "{{ AYAQA_PHP_MODULE_CONFIG_DIR }}/xdebug.ini"
    list_of_php_packages: [
      "php8.0-cli",
      "php8.0-common",
      "php8.0-mbstring",
      "php8.0-bcmath",
      "php8.0-gd",
      "php8.0-xdebug",
      "php8.0-curl",
      "php8.0-mysql",
      "php8.0-imap",
      "php8.0-dom",
      "php8.0-intl"
    ]

  tasks:
    - name: "DEBUG: Dump variables."
      debug:
        msg:
          - "----------------- Vars ---------------------"
          - "Name: {{ AYAQA_PROJECT_NAME }}"
          - "Tag: {{ AYAQA_PROJECT_TAG }}"
          - "Build Stage: {{ AYAQA_INFRA_BUILD_STAGE }}"
          - "Build Debug: {{ AYAQA_INFRA_DEBUG }}"
          - "App Stage: {{ AYAQA_APP_ENV }}"
          - "App Debug: {{ AYAQA_APP_DEBUG }}"
          - "----------------- ### ---------------------"
          - "PHP Version: {{ php_version }}"
          - "PHP CLI dir: {{ php_cli_config_dir }}"
          - "Xdebug port: {{ AYAQA_XDEBUG_PORT }}"
          - "Xdebug cli path: {{ php_xdebug_module_config_file }}"
          - "PHP packages: {{ list_of_php_packages | join(', ') }}"
          - "----------------- End ---------------------"
      tags:
        - debug_info

  roles:
    - php
