name: ayaQA Push

on:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        path: infra
      - name: Install required linux dependencies
        run: |
          ls -la /
          bash /infra/.github/files/scripts/install_ci.sh
        shell: bash
      - name: "Setup packer: 1.6.5"
        uses: hashicorp-contrib/setup-packer@v1
        with:
          packer-version: 1.6.5

  build-image-base:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v2
      - name: "Login to Docker Hub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Setup before start build
        run: |
          bash ~/.github/files/scripts/setup_ci.sh
        shell: bash
      - name: "Build image: base"
        run: |
          set -x
          export TERM=xterm-256color 

          make -s build_remote IMAGE_NAME=base
          make -s tag_hub IMAGE_NAME=base
          make -s push_hub IMAGE_NAME=base
          make -s clear IMAGE_NAME=base

  build-image-dev:
    runs-on: ubuntu-latest
    needs: [prepare, build-image-base]
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Setup before start build
        run: |
          bash .github/files/scripts/setup_ci.sh
        shell: bash
      - name: "Build image: dev"
        run: |
          set -x
          export TERM=xterm-256color 

          make -s build_remote IMAGE_NAME=dev
          make -s tag_hub IMAGE_NAME=dev
          make -s push_hub IMAGE_NAME=dev
          make -s clear IMAGE_NAME=dev
      